---
apiVersion: v1
kind: Pod
metadata:
  name: laptop
  labels:
    env: dev
spec:
  containers:
    - name: friends
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: flm-service
spec:
  type: ClusterIP
  selector:
    env: dev
  ports:
    - port: 80
      targetPort: 80
