---
apiVersion: v1
kind: Pod
metadata:
  name: nodeport
  labels:
    env: prod
spec:
  containers:
    - name: port-1
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: serviceport
spec:
  type: NodePort
  selector:
    env: prod
  ports:
    - port: 80
      targetPort: 80
