---
apiVersion: v1
kind: ReplicationController
metadata:
  name: control
spec:
  replicas: 2
  selector:
    app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont-1
          image: nginx
          ports:
            - containerPort: 80
